// poly_apps/matrixui/components/ConfirmDialog.tsx

import React from 'react';

export interface ConfirmDialogOptions {
  title: string;
  message: string;
  confirmText?: string;
  cancelText?: string;
  type?: 'danger' | 'warning' | 'info';
}

interface ConfirmDialogProps extends ConfirmDialogOptions {
  onConfirm: () => void;
  onCancel: () => void;
}

export const ConfirmDialog: React.FC<ConfirmDialogProps> = ({
  title,
  message,
  confirmText = 'Confirm',
  cancelText = 'Cancel',
  type = 'info',
  onConfirm,
  onCancel
}) => {
  const colors = {
    danger: {
      confirm: 'bg-[#ff2a6d] hover:bg-[#ff2a6d]/80 text-white',
      icon: 'ph-warning text-[#ff2a6d]',
      border: 'border-[#ff2a6d]/30'
    },
    warning: {
      confirm: 'bg-[#ffd60a] hover:bg-[#ffd60a]/80 text-black',
      icon: 'ph-warning text-[#ffd60a]',
      border: 'border-[#ffd60a]/30'
    },
    info: {
      confirm: 'bg-[#00f2ff] hover:bg-[#00f2ff]/80 text-white',
      icon: 'ph-info text-[#00f2ff]',
      border: 'border-[#00f2ff]/30'
    }
  };

  const style = colors[type];

  return (
    <div
      className="fixed inset-0 z-[90] flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm animate-fade-in"
      onClick={onCancel}
    >
      <div
        className={`
          w-full max-w-md bg-[#0a0c10] border rounded-xl shadow-[0_0_50px_rgba(0,0,0,0.5)]
          overflow-hidden animate-scale-in ${style.border}
        `}
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="h-14 border-b border-white/10 flex items-center gap-3 px-6 bg-white/[0.02]">
          <i className={`ph ${style.icon} text-xl`}></i>
          <h3 className="text-sm font-bold text-white tracking-wide flex-1">{title}</h3>
        </div>

        {/* Body */}
        <div className="p-6">
          <p className="text-sm text-slate-300 leading-relaxed">{message}</p>
        </div>

        {/* Footer */}
        <div className="h-14 border-t border-white/10 flex items-center justify-end gap-3 px-6 bg-white/[0.02]">
          <button
            onClick={onCancel}
            className="px-4 py-2 rounded-lg bg-white/5 hover:bg-white/10 border border-white/10 text-slate-300 hover:text-white transition-colors text-sm font-medium"
          >
            {cancelText}
          </button>
          <button
            onClick={onConfirm}
            className={`px-4 py-2 rounded-lg ${style.confirm} transition-colors text-sm font-medium`}
          >
            {confirmText}
          </button>
        </div>
      </div>
    </div>
  );
};

// Hook for managing confirm dialogs
export const useConfirmDialog = () => {
  const [dialog, setDialog] = React.useState<ConfirmDialogOptions | null>(null);
  const [resolveCallback, setResolveCallback] = React.useState<((confirmed: boolean) => void) | null>(null);

  const showConfirmDialog = (options: ConfirmDialogOptions): Promise<boolean> => {
    return new Promise((resolve) => {
      setDialog(options);
      setResolveCallback(() => resolve);
    });
  };

  const handleConfirm = () => {
    if (resolveCallback) {
      resolveCallback(true);
    }
    setDialog(null);
    setResolveCallback(null);
  };

  const handleCancel = () => {
    if (resolveCallback) {
      resolveCallback(false);
    }
    setDialog(null);
    setResolveCallback(null);
  };

  return {
    dialog,
    showConfirmDialog,
    ConfirmDialogComponent: dialog ? (
      <ConfirmDialog {...dialog} onConfirm={handleConfirm} onCancel={handleCancel} />
    ) : null
  };
};

// apps/mcp-chrome/app/chrome-extension/entrypoints/popup/components/ConfirmDialog.vue
<template>
  <div v-if="visible" class="fixed inset-0 bg-black/70 flex items-center justify-center z-50" @click.self="$emit('cancel')">
    <div class="bg-slate-900 border border-slate-700 rounded-xl shadow-2xl max-w-sm w-full mx-4 overflow-hidden">
      <div class="flex items-center gap-3 px-4 py-3 border-b border-slate-700">
        <span class="text-lg">{{ icon }}</span>
        <h3 class="text-sm font-bold text-slate-200">{{ title }}</h3>
      </div>

      <div class="px-4 py-3 space-y-2">
        <p class="text-[10px] text-slate-300 leading-relaxed">{{ message }}</p>

        <ul v-if="items && items.length > 0" class="space-y-1 pl-4 text-[10px] text-slate-400">
          <li v-for="item in items" :key="item" class="list-disc">{{ item }}</li>
        </ul>

        <div v-if="warning" class="p-2 bg-rose-500/10 border-l-2 border-rose-500 rounded">
          <strong class="text-[10px] text-rose-400">{{ warning }}</strong>
        </div>
      </div>

      <div class="flex gap-2 px-4 py-3 bg-slate-950 border-t border-slate-700">
        <button class="flex-1 px-3 py-1.5 bg-slate-700 text-slate-300 text-[10px] font-bold rounded-md hover:bg-slate-600 transition-colors" @click="$emit('cancel')">
          {{ cancelText }}
        </button>
        <button
          class="flex-1 px-3 py-1.5 bg-rose-600 text-white text-[10px] font-bold rounded-md hover:bg-rose-700 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
          :disabled="isConfirming"
          @click="$emit('confirm')"
        >
          {{ isConfirming ? confirmingText : confirmText }}
        </button>
      </div>
    </div>
  </div>
</template>

<script lang="ts" setup>
import { getMessage } from '@/utils/i18n';
interface Props {
  visible: boolean;
  title: string;
  message: string;
  items?: string[];
  warning?: string;
  icon?: string;
  confirmText?: string;
  cancelText?: string;
  confirmingText?: string;
  isConfirming?: boolean;
}

interface Emits {
  (e: 'confirm'): void;
  (e: 'cancel'): void;
}

withDefaults(defineProps<Props>(), {
  icon: '⚠️',
  confirmText: getMessage('confirmButton'),
  cancelText: getMessage('cancelButton'),
  confirmingText: getMessage('processingStatus'),
  isConfirming: false,
});

defineEmits<Emits>();
</script>
