// poly_apps/wordflow-ai/pages/Auth/ForgotPassword.tsx
import React, { useState, useContext } from 'react';
import { AppContext } from '../../contexts/AppContext';
import { ApiCenter } from '../../services/ApiCenter';

const ForgotPassword = () => {
  const { t, navigate } = useContext(AppContext);
  const [email, setEmail] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [success, setSuccess] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    setSuccess(false);

    if (!email) {
      setError(t('auth.emailRequired') || 'Email is required');
      return;
    }

    setLoading(true);

    try {
      const response = await ApiCenter.auth.forgotPassword(email);

      if (response.success) {
        setSuccess(true);
        setError('');
      } else {
        setError(response.error?.message || 'Failed to send reset email');
      }
    } catch (err: any) {
      setError(err.message || 'An error occurred');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-blue-50 via-white to-purple-50 dark:from-slate-900 dark:via-slate-800 dark:to-slate-900 p-5">
      <div className="w-full sm:max-w-2xl md:max-w-4xl lg:max-w-5xl">
        {/* Back Button */}
        <button
          onClick={() => navigate('/login')}
          className="mb-4 flex items-center gap-2 text-slate-600 dark:text-slate-400 hover:text-blue-500 dark:hover:text-blue-400 transition-colors"
        >
          <span>←</span>
          <span>{t('common.back')}</span>
        </button>

        {/* Card */}
        <div className="glass-panel bg-white/80 dark:bg-slate-800/80 backdrop-blur-xl rounded-3xl shadow-2xl p-8 border border-white/20">
          {/* Header */}
          <div className="text-center mb-8">
            <h1 className="text-3xl font-bold text-slate-800 dark:text-white mb-2">
              {t('auth.forgotPassword')}
            </h1>
            <p className="text-slate-600 dark:text-slate-400 text-sm">
              Enter your email to receive password reset instructions
            </p>
          </div>

          {success ? (
            /* Success Message */
            <div className="text-center py-8">
              <div className="w-16 h-16 bg-green-100 dark:bg-green-900/30 rounded-full flex items-center justify-center mx-auto mb-4">
                <span className="text-3xl">✓</span>
              </div>
              <h2 className="text-xl font-bold text-slate-800 dark:text-white mb-2">
                Check Your Email
              </h2>
              <p className="text-slate-600 dark:text-slate-400 mb-6">
                We've sent password reset instructions to <strong>{email}</strong>
              </p>
              <button
                onClick={() => navigate('/login')}
                className="w-full py-4 bg-blue-500 text-white rounded-xl font-bold hover:bg-blue-600 transition-all"
              >
                {t('common.back')} to Login
              </button>
            </div>
          ) : (
            /* Form */
            <form onSubmit={handleSubmit} className="space-y-6">
              {error && (
                <div className="p-4 bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-xl text-red-600 dark:text-red-400 text-sm">
                  {error}
                </div>
              )}

              <div>
                <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-2">
                  {t('auth.email')}
                </label>
                <input
                  type="email"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  placeholder="your.email@example.com"
                  disabled={loading}
                  className="w-full p-4 rounded-xl glass-panel bg-white/40 dark:bg-black/20 outline-none focus:ring-2 ring-blue-400 dark:text-white transition-all disabled:opacity-50"
                  autoComplete="email"
                />
              </div>

              <button
                type="submit"
                disabled={loading}
                className="w-full py-4 bg-gradient-to-r from-blue-500 to-purple-500 text-white rounded-xl font-bold hover:shadow-lg hover:scale-105 transition-all disabled:opacity-50 disabled:cursor-not-allowed disabled:hover:scale-100"
              >
                {loading ? t('common.loading') : 'Send Reset Link'}
              </button>

              <div className="text-center">
                <button
                  type="button"
                  onClick={() => navigate('/login')}
                  className="text-sm text-blue-500 hover:text-blue-600 dark:text-blue-400 dark:hover:text-blue-300"
                >
                  Remember your password? {t('auth.login')}
                </button>
              </div>
            </form>
          )}
        </div>
      </div>
    </div>
  );
};

export default ForgotPassword;

// poly_apps/top-router/web/admin-spa/src/views/auth/ForgotPassword.vue
<template>
  <div class="flex min-h-screen items-center justify-center p-4 sm:p-6">
    <!-- 主题切换按钮 - 固定在右上角 -->
    <div class="fixed right-4 top-4 z-50">
      <ThemeToggle mode="dropdown" />
    </div>

    <div
      class="glass-strong w-full max-w-md rounded-xl p-6 shadow-2xl sm:rounded-2xl sm:p-8 md:rounded-3xl md:p-10"
    >
      <div class="mb-6 text-center sm:mb-8">
        <div
          class="mx-auto mb-4 flex h-16 w-16 items-center justify-center overflow-hidden rounded-xl border border-gray-300/30 bg-gradient-to-br from-blue-500/20 to-purple-500/20 backdrop-blur-sm sm:mb-6 sm:h-20 sm:w-20 sm:rounded-2xl"
        >
          <template v-if="!oemLoading">
            <img
              v-if="authStore.oemSettings.siteIconData || authStore.oemSettings.siteIcon"
              alt="Logo"
              class="h-10 w-10 object-contain sm:h-12 sm:w-12"
              :src="authStore.oemSettings.siteIconData || authStore.oemSettings.siteIcon"
              @error="(e) => (e.target.style.display = 'none')"
            />
            <i v-else class="fas fa-key text-2xl text-gray-700 sm:text-3xl" />
          </template>
          <div v-else class="h-10 w-10 animate-pulse rounded bg-gray-300/50 sm:h-12 sm:w-12" />
        </div>

        <template v-if="!oemLoading && authStore.oemSettings.siteName">
          <h1 class="header-title mb-2 text-2xl font-bold text-white sm:text-3xl">忘记密码</h1>
        </template>
        <div
          v-else-if="oemLoading"
          class="mx-auto mb-2 h-8 w-48 animate-pulse rounded bg-gray-300/50 sm:h-9 sm:w-64"
        />

        <p class="text-sm text-gray-600 dark:text-gray-400 sm:text-base">
          输入您的邮箱地址，我们将发送密码重置链接
        </p>
      </div>

      <!-- 成功消息 -->
      <div
        v-if="successMessage"
        class="mb-4 rounded-lg border border-green-500/30 bg-green-500/20 p-3 text-center text-xs text-green-800 backdrop-blur-sm dark:text-green-400 sm:mb-6 sm:rounded-xl sm:p-4 sm:text-sm"
      >
        <i class="fas fa-check-circle mr-2" />{{ successMessage }}
      </div>

      <!-- 表单 -->
      <form v-if="!successMessage" class="space-y-4 sm:space-y-6" @submit.prevent="handleSubmit">
        <div>
          <label
            class="mb-2 block text-sm font-semibold text-gray-900 dark:text-gray-100 sm:mb-3"
            for="email"
          >
            邮箱地址
          </label>
          <input
            id="email"
            v-model="email"
            autocomplete="email"
            class="form-input w-full"
            name="email"
            placeholder="请输入您的邮箱地址"
            required
            type="email"
          />
        </div>

        <button
          class="btn btn-primary w-full px-4 py-3 text-base font-semibold sm:px-6 sm:py-4 sm:text-lg"
          :disabled="isLoading"
          type="submit"
        >
          <i v-if="!isLoading" class="fas fa-paper-plane mr-2" />
          <div v-if="isLoading" class="loading-spinner mr-2" />
          {{ isLoading ? '发送中...' : '发送重置链接' }}
        </button>
      </form>

      <!-- 错误消息 -->
      <div
        v-if="errorMessage"
        class="mt-4 rounded-lg border border-red-500/30 bg-red-500/20 p-3 text-center text-xs text-red-800 backdrop-blur-sm dark:text-red-400 sm:mt-6 sm:rounded-xl sm:p-4 sm:text-sm"
      >
        <i class="fas fa-exclamation-triangle mr-2" />{{ errorMessage }}
      </div>

      <!-- 返回登录 -->
      <div class="mt-4 text-center sm:mt-6">
        <router-link
          class="text-sm text-blue-600 hover:text-blue-700 hover:underline dark:text-blue-400 dark:hover:text-blue-300 sm:text-base"
          to="/auth/admin-login"
        >
          <i class="fas fa-arrow-left mr-2" />返回登录
        </router-link>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { useAuthStore } from '@/stores/auth'
import { apiClient } from '@/config/api'
import ThemeToggle from '@/components/common/ThemeToggle.vue'

const authStore = useAuthStore()

// 状态
const email = ref('')
const isLoading = ref(false)
const errorMessage = ref('')
const successMessage = ref('')
const oemLoading = ref(true)

// 加载OEM设置
onMounted(async () => {
  try {
    await authStore.loadOemSettings()
  } catch (error) {
    console.error('Failed to load OEM settings:', error)
  } finally {
    oemLoading.value = false
  }
})

// 处理表单提交
const handleSubmit = async () => {
  if (!email.value.trim()) {
    errorMessage.value = '请输入邮箱地址'
    return
  }

  // 简单的邮箱格式验证
  const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/
  if (!emailRegex.test(email.value)) {
    errorMessage.value = '请输入有效的邮箱地址'
    return
  }

  errorMessage.value = ''
  successMessage.value = ''
  isLoading.value = true

  try {
    const response = await apiClient.post('/users/forgot-password', {
      email: email.value.trim()
    })

    if (response.success) {
      successMessage.value = response.message || '密码重置邮件已发送，请查收邮箱'
      email.value = ''
    } else {
      errorMessage.value = response.message || '发送失败，请稍后重试'
    }
  } catch (error) {
    console.error('Forgot password error:', error)
    errorMessage.value = error.message || '发送失败，请稍后重试'
  } finally {
    isLoading.value = false
  }
}
</script>

<style scoped>
/* 继承全局样式，无需额外样式 */
</style>
