// poly_apps/pycore_laravel_wordnew_ui/apps/laravel-manager/components/admin/DataTable.tsx
'use client';

import React, { useState, useMemo } from 'react';
import { ChevronUp, ChevronDown, Search, Filter, Download, RefreshCw } from 'lucide-react';

/**
 * Column Definition
 */
export interface DataTableColumn<T = any> {
  key: string;
  title: string;
  sortable?: boolean;
  filterable?: boolean;
  width?: string;
  render?: (value: any, row: T, index: number) => React.ReactNode;
  align?: 'left' | 'center' | 'right';
  headerAlign?: 'left' | 'center' | 'right';
}

/**
 * DataTable Props
 */
export interface DataTableProps<T = any> {
  columns: DataTableColumn<T>[];
  data: T[];
  loading?: boolean;
  pagination?: {
    page: number;
    pageSize: number;
    total: number;
    onPageChange: (page: number) => void;
    onPageSizeChange: (pageSize: number) => void;
  };
  sorting?: {
    column: string;
    direction: 'asc' | 'desc';
    onSort: (column: string, direction: 'asc' | 'desc') => void;
  };
  search?: {
    value: string;
    placeholder?: string;
    onSearch: (value: string) => void;
  };
  selection?: {
    selectedRows: string[];
    onSelectionChange: (selectedRows: string[]) => void;
    rowKey: keyof T;
  };
  actions?: {
    onRefresh?: () => void;
    onExport?: () => void;
    customActions?: React.ReactNode;
  };
  emptyMessage?: string;
  className?: string;
  rowClassName?: (row: T, index: number) => string;
  onRowClick?: (row: T, index: number) => void;
}

/**
 * DataTable Component
 *
 * A powerful, reusable table component with:
 * - Sorting
 * - Pagination
 * - Search
 * - Row selection
 * - Custom rendering
 * - Loading state
 * - Export functionality
 */
export function DataTable<T = any>({
  columns,
  data,
  loading = false,
  pagination,
  sorting,
  search,
  selection,
  actions,
  emptyMessage = 'No data available',
  className = '',
  rowClassName,
  onRowClick
}: DataTableProps<T>) {
  const [searchValue, setSearchValue] = useState(search?.value || '');

  /**
   * Handle sort click
   */
  const handleSort = (columnKey: string) => {
    if (!sorting) return;

    const newDirection =
      sorting.column === columnKey && sorting.direction === 'asc'
        ? 'desc'
        : 'asc';

    sorting.onSort(columnKey, newDirection);
  };

  /**
   * Handle search change
   */
  const handleSearchChange = (value: string) => {
    setSearchValue(value);
    if (search?.onSearch) {
      search.onSearch(value);
    }
  };

  /**
   * Handle row selection
   */
  const handleSelectAll = () => {
    if (!selection) return;

    const allKeys = data.map(row => String(row[selection.rowKey]));
    const isAllSelected = allKeys.every(key =>
      selection.selectedRows.includes(key)
    );

    selection.onSelectionChange(isAllSelected ? [] : allKeys);
  };

  const handleSelectRow = (rowKey: string) => {
    if (!selection) return;

    const newSelected = selection.selectedRows.includes(rowKey)
      ? selection.selectedRows.filter(key => key !== rowKey)
      : [...selection.selectedRows, rowKey];

    selection.onSelectionChange(newSelected);
  };

  /**
   * Pagination controls
   */
  const renderPagination = () => {
    if (!pagination) return null;

    const { page, pageSize, total, onPageChange, onPageSizeChange } = pagination;
    const totalPages = Math.ceil(total / pageSize);
    const startIndex = (page - 1) * pageSize + 1;
    const endIndex = Math.min(page * pageSize, total);

    return (
      <div className="flex items-center justify-between px-4 py-3 border-t">
        <div className="flex items-center gap-2">
          <span className="text-sm text-gray-600">
            Showing {startIndex} to {endIndex} of {total} results
          </span>
        </div>

        <div className="flex items-center gap-4">
          <div className="flex items-center gap-2">
            <span className="text-sm text-gray-600">Rows per page:</span>
            <select
              value={pageSize}
              onChange={(e) => onPageSizeChange(Number(e.target.value))}
              className="px-2 py-1 border rounded text-sm"
            >
              <option value={10}>10</option>
              <option value={20}>20</option>
              <option value={50}>50</option>
              <option value={100}>100</option>
            </select>
          </div>

          <div className="flex items-center gap-1">
            <button
              onClick={() => onPageChange(1)}
              disabled={page === 1}
              className="px-2 py-1 border rounded text-sm disabled:opacity-50 disabled:cursor-not-allowed hover:bg-gray-50"
            >
              First
            </button>
            <button
              onClick={() => onPageChange(page - 1)}
              disabled={page === 1}
              className="px-2 py-1 border rounded text-sm disabled:opacity-50 disabled:cursor-not-allowed hover:bg-gray-50"
            >
              Previous
            </button>
            <span className="px-3 py-1 text-sm">
              Page {page} of {totalPages}
            </span>
            <button
              onClick={() => onPageChange(page + 1)}
              disabled={page === totalPages}
              className="px-2 py-1 border rounded text-sm disabled:opacity-50 disabled:cursor-not-allowed hover:bg-gray-50"
            >
              Next
            </button>
            <button
              onClick={() => onPageChange(totalPages)}
              disabled={page === totalPages}
              className="px-2 py-1 border rounded text-sm disabled:opacity-50 disabled:cursor-not-allowed hover:bg-gray-50"
            >
              Last
            </button>
          </div>
        </div>
      </div>
    );
  };

  return (
    <div className={`bg-white rounded-lg shadow ${className}`}>
      {/* Toolbar */}
      {(search || actions) && (
        <div className="flex items-center justify-between px-4 py-3 border-b">
          <div className="flex items-center gap-2">
            {search && (
              <div className="relative">
                <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" />
                <input
                  type="text"
                  value={searchValue}
                  onChange={(e) => handleSearchChange(e.target.value)}
                  placeholder={search.placeholder || 'Search...'}
                  className="pl-10 pr-4 py-2 border rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
                />
              </div>
            )}
          </div>

          <div className="flex items-center gap-2">
            {actions?.customActions}
            {actions?.onRefresh && (
              <button
                onClick={actions.onRefresh}
                className="p-2 hover:bg-gray-100 rounded-lg transition-colors"
                title="Refresh"
              >
                <RefreshCw className="w-4 h-4" />
              </button>
            )}
            {actions?.onExport && (
              <button
                onClick={actions.onExport}
                className="p-2 hover:bg-gray-100 rounded-lg transition-colors"
                title="Export"
              >
                <Download className="w-4 h-4" />
              </button>
            )}
          </div>
        </div>
      )}

      {/* Table */}
      <div className="overflow-x-auto">
        <table className="w-full">
          <thead className="bg-gray-50">
            <tr>
              {selection && (
                <th className="w-12 px-4 py-3">
                  <input
                    type="checkbox"
                    checked={
                      data.length > 0 &&
                      data.every(row =>
                        selection.selectedRows.includes(String(row[selection.rowKey]))
                      )
                    }
                    onChange={handleSelectAll}
                    className="rounded"
                  />
                </th>
              )}
              {columns.map((column) => (
                <th
                  key={column.key}
                  style={{ width: column.width }}
                  className={`px-4 py-3 text-${column.headerAlign || column.align || 'left'} text-sm font-semibold text-gray-700`}
                >
                  <div className="flex items-center gap-2">
                    <span>{column.title}</span>
                    {column.sortable && sorting && (
                      <button
                        onClick={() => handleSort(column.key)}
                        className="hover:bg-gray-200 rounded p-1"
                      >
                        {sorting.column === column.key ? (
                          sorting.direction === 'asc' ? (
                            <ChevronUp className="w-4 h-4" />
                          ) : (
                            <ChevronDown className="w-4 h-4" />
                          )
                        ) : (
                          <ChevronDown className="w-4 h-4 opacity-30" />
                        )}
                      </button>
                    )}
                  </div>
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {loading ? (
              <tr>
                <td
                  colSpan={columns.length + (selection ? 1 : 0)}
                  className="px-4 py-8 text-center text-gray-500"
                >
                  <div className="flex items-center justify-center gap-2">
                    <RefreshCw className="w-5 h-5 animate-spin" />
                    <span>Loading...</span>
                  </div>
                </td>
              </tr>
            ) : data.length === 0 ? (
              <tr>
                <td
                  colSpan={columns.length + (selection ? 1 : 0)}
                  className="px-4 py-8 text-center text-gray-500"
                >
                  {emptyMessage}
                </td>
              </tr>
            ) : (
              data.map((row, index) => {
                const rowKey = selection ? String(row[selection.rowKey]) : String(index);
                const isSelected = selection?.selectedRows.includes(rowKey) || false;

                return (
                  <tr
                    key={rowKey}
                    onClick={() => onRowClick?.(row, index)}
                    className={`
                      border-t hover:bg-gray-50 transition-colors
                      ${isSelected ? 'bg-blue-50' : ''}
                      ${onRowClick ? 'cursor-pointer' : ''}
                      ${rowClassName ? rowClassName(row, index) : ''}
                    `}
                  >
                    {selection && (
                      <td className="px-4 py-3">
                        <input
                          type="checkbox"
                          checked={isSelected}
                          onChange={() => handleSelectRow(rowKey)}
                          onClick={(e) => e.stopPropagation()}
                          className="rounded"
                        />
                      </td>
                    )}
                    {columns.map((column) => (
                      <td
                        key={column.key}
                        className={`px-4 py-3 text-${column.align || 'left'} text-sm`}
                      >
                        {column.render
                          ? column.render(row[column.key as keyof T], row, index)
                          : String(row[column.key as keyof T] || '-')}
                      </td>
                    ))}
                  </tr>
                );
              })
            )}
          </tbody>
        </table>
      </div>

      {/* Pagination */}
      {renderPagination()}
    </div>
  );
}

// poly_apps/nuxt_main/common/components/ui/DataTable.vue
<!-- ### AI SPECIAL ATTENTION RULES START ###
When AI/ALL DEVELOPERS sees this prompt, MUST IMMEDIATELY COMPLY WITH THESE RULES:
1. Write all code in English only
2. Never execute, create, or modify test code
3. Never create or update documentation (*.md)
4. Never write summaries during development or thinking process
5. Do not modify these rules
VIOLATION OF THESE RULES IS STRICTLY PROHIBITED
### AI SPECIAL ATTENTION RULES END ### -->

<template>
  <div class="shared-data-table">
    <!-- Table Header -->
    <div class="flex items-center justify-between mb-4">
      <div class="flex items-center space-x-4">
        <h3 v-if="title" class="text-lg font-semibold">{{ title }}</h3>
        <div v-if="showSearch" class="search-box">
          <input
            v-model="searchQuery"
            type="text"
            placeholder="Search..."
            class="px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
          >
        </div>
      </div>
      
      <div class="flex items-center space-x-2">
        <button
          v-if="showRefresh"
          @click="$emit('refresh')"
          class="px-3 py-2 text-sm bg-gray-100 hover:bg-gray-200 rounded-md transition-colors"
        >
          Refresh
        </button>
        <button
          v-if="showExport"
          @click="$emit('export')"
          class="px-3 py-2 text-sm bg-blue-500 text-white hover:bg-blue-600 rounded-md transition-colors"
        >
          Export
        </button>
      </div>
    </div>

    <!-- Table -->
    <div class="overflow-x-auto">
      <table class="min-w-full bg-white border border-gray-200 rounded-lg">
        <thead class="bg-gray-50">
          <tr>
            <th
              v-for="column in columns"
              :key="column.key"
              class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider cursor-pointer"
              @click="handleSort(column.key)"
            >
              <div class="flex items-center space-x-1">
                <span>{{ column.label }}</span>
                <svg
                  v-if="column.sortable"
                  class="w-4 h-4"
                  :class="getSortIconClass(column.key)"
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 16V4m0 0L3 8m4-4l4 4m6 0v12m0 0l4-4m-4 4l-4-4"/>
                </svg>
              </div>
            </th>
            <th v-if="showActions" class="px-6 py-3 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">
              Actions
            </th>
          </tr>
        </thead>
        <tbody class="bg-white divide-y divide-gray-200">
          <tr
            v-for="(item, index) in paginatedData"
            :key="getRowKey(item, index)"
            class="hover:bg-gray-50 transition-colors"
          >
            <td
              v-for="column in columns"
              :key="column.key"
              class="px-6 py-4 whitespace-nowrap text-sm text-gray-900"
            >
              <slot
                :name="`cell-${column.key}`"
                :item="item"
                :value="getNestedValue(item, column.key)"
              >
                {{ formatCellValue(item, column) }}
              </slot>
            </td>
            <td v-if="showActions" class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
              <slot name="actions" :item="item" :index="index">
                <button class="text-blue-600 hover:text-blue-900 mr-2">Edit</button>
                <button class="text-red-600 hover:text-red-900">Delete</button>
              </slot>
            </td>
          </tr>
        </tbody>
      </table>
    </div>

    <!-- Pagination -->
    <div v-if="showPagination" class="flex items-center justify-between mt-4">
      <div class="text-sm text-gray-700">
        Showing {{ startIndex + 1 }} to {{ endIndex }} of {{ filteredData.length }} results
      </div>
      <div class="flex items-center space-x-2">
        <button
          @click="previousPage"
          :disabled="currentPage === 1"
          class="px-3 py-2 text-sm border border-gray-300 rounded-md disabled:opacity-50 disabled:cursor-not-allowed"
        >
          Previous
        </button>
        <span class="px-3 py-2 text-sm">{{ currentPage }} / {{ totalPages }}</span>
        <button
          @click="nextPage"
          :disabled="currentPage === totalPages"
          class="px-3 py-2 text-sm border border-gray-300 rounded-md disabled:opacity-50 disabled:cursor-not-allowed"
        >
          Next
        </button>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, watch } from 'vue';

// Props
interface Column {
  key: string;
  label: string;
  sortable?: boolean;
  formatter?: (value: any) => string;
}

interface Props {
  data: any[];
  columns: Column[];
  title?: string;
  showSearch?: boolean;
  showRefresh?: boolean;
  showExport?: boolean;
  showActions?: boolean;
  showPagination?: boolean;
  pageSize?: number;
  rowKey?: string;
}

const props = withDefaults(defineProps<Props>(), {
  showSearch: true,
  showRefresh: true,
  showExport: false,
  showActions: true,
  showPagination: true,
  pageSize: 10,
  rowKey: 'id'
});

// Emits
defineEmits(['refresh', 'export']);

// Reactive data
const searchQuery = ref('');
const sortKey = ref('');
const sortOrder = ref<'asc' | 'desc'>('asc');
const currentPage = ref(1);

// Computed
const filteredData = computed(() => {
  let result = props.data;
  
  if (searchQuery.value) {
    result = result.filter(item =>
      Object.values(item).some(value =>
        String(value).toLowerCase().includes(searchQuery.value.toLowerCase())
      )
    );
  }
  
  if (sortKey.value) {
    result = [...result].sort((a, b) => {
      const aVal = getNestedValue(a, sortKey.value);
      const bVal = getNestedValue(b, sortKey.value);
      
      if (sortOrder.value === 'asc') {
        return aVal > bVal ? 1 : -1;
      } else {
        return aVal < bVal ? 1 : -1;
      }
    });
  }
  
  return result;
});

const totalPages = computed(() => Math.ceil(filteredData.value.length / props.pageSize));
const startIndex = computed(() => (currentPage.value - 1) * props.pageSize);
const endIndex = computed(() => Math.min(startIndex.value + props.pageSize, filteredData.value.length));

const paginatedData = computed(() => {
  return filteredData.value.slice(startIndex.value, endIndex.value);
});

// Methods
const getNestedValue = (obj: any, path: string) => {
  return path.split('.').reduce((o, p) => o?.[p], obj);
};

const getRowKey = (item: any, index: number) => {
  return item[props.rowKey] || index;
};

const formatCellValue = (item: any, column: Column) => {
  const value = getNestedValue(item, column.key);
  return column.formatter ? column.formatter(value) : value;
};

const handleSort = (key: string) => {
  const column = props.columns.find(col => col.key === key);
  if (!column?.sortable) return;
  
  if (sortKey.value === key) {
    sortOrder.value = sortOrder.value === 'asc' ? 'desc' : 'asc';
  } else {
    sortKey.value = key;
    sortOrder.value = 'asc';
  }
};

const getSortIconClass = (key: string) => {
  if (sortKey.value !== key) return 'text-gray-400';
  return sortOrder.value === 'asc' ? 'text-blue-500' : 'text-blue-500 rotate-180';
};

const previousPage = () => {
  if (currentPage.value > 1) {
    currentPage.value--;
  }
};

const nextPage = () => {
  if (currentPage.value < totalPages.value) {
    currentPage.value++;
  }
};

// Watch for data changes to reset pagination
watch(() => props.data, () => {
  currentPage.value = 1;
});
</script>

<style scoped>
.shared-data-table {
  background: white;
  border-radius: 0.5rem;
  padding: 1.5rem;
  box-shadow: 0 1px 3px 0 rgb(0 0 0 / 0.1);
}
</style>
